services:
  mc:
    container_name: ombrelis
    image: itzg/minecraft-server
    environment:
      TYPE: MODRINTH
      VERSION: "1.21.1"
      EULA: true

      INIT_MEMORY: 6G
      MEMORY: 12G
      USE_AIKAR_FLAGS: true

      PVP: true
      ALLOW_FLIGHT: true
      ENABLE_COMMAND_BLOCK: true
      DIFFICULTY: "normal"
      MOTD: "§l§cPIKMINE§r | Ombrelis"

      MODRINTH_MODPACK: ${MODRINTH_MODPACK}
      DATAPACKS: "datapacks"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
